#!/bin/sh
#
# cloudboot-server
#
# chkconfig: 2345 30 70

### BEGIN INIT INFO
# Provides: cloudboot-server
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Default-Start:  2345
# Default-Stop: 70
# Short-Description: run cron daemon
### END INIT INFO

# set -x

prog="cloudboot-server"

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    echo -n $"Starting $prog: "
    # nohup $prog &>/dev/null &
    nohup $prog &> /var/log/server.log &
    sleep 1s
    pidof /usr/bin/$prog &>/dev/null && success || failure
    echo
}

stop() {
    echo -n $"Stopping $prog: "
    kill `pidof /usr/bin/$prog` &>/dev/null && success || failure
    echo
}

restart() {
    stop && start
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac
exit $?
